### PR TITLE
Version updates to handle security warnings

### PR DESCRIPTION
**Pull request by brokenintuition**
This updates almost everything to handle some security warnings, including pinning a good version of gopkg.in/yaml.v2 because some dependencies haven't updated yet.

Netezza driver was removed from the image because it's a proprietary driver that shouldn't be bundled in the docker image. It's not referenced directly in the code. If necessary, consumers can use the sql-agent image as a base and add the driver themselves.

### CODE REVIEW

**Comment by brokenintuition** [comment]
Just noting I've tested this with postgres, haven't tested any of the others because I don't have easy access to each of the different db types this supports.

**Comment by murphyke** [comment]
@brokenintuition Where was lib/netezza coming from, anyway? I am guessing the netezza support is in there because somebody must have needed it, so it would be good to update the README to tell people how to install it if they need to.

**Comment by brokenintuition** [comment]
Byron sent me the binary the first time I had to build this. I'm not sure why it was included originally.

As far as I can tell, you can't download the driver without an active support contract, so I wouldn't know what to include in install instructions for anyone that needs it.

**Comment by murphyke** [comment]
> Byron sent me the binary the first time I had to build this. I'm not sure why it was included originally.

OK, that's a bit mysterious.

Yeah, the only thing you could include would be the instructions in the Dockerfile that we are taking out.

> As far as I can tell, you can't download the driver without an active support contract

I tried for a few minutes to find out how to download the right client package, and I was utterly defeated, so I am guessing you're right about that.

OK, I guess we just wait until somebody complains. I'll approve.

**Review by murphyke — APPROVED** [review]

**Pull request merged**
